### ISSUE TITLE
 HTTP error fetching URL. Status=403,

### ISSUE THREAD

**Issue by hoofkhanh** [Spoocy99/GeniusAPI#1]
This is my issue, maybe need buy a package of genius ?

org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=[https://genius.com/Kendrick-lamar-humble-lyrics]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:912)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:851)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:345)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:330)
	at dev.spoocy.genius.core.Client.getLyrics(Client.java:35)
	at dev.spoocy.genius.Main.main(Main.java:30)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "dev.spoocy.genius.data.Lyrics.getAsPlain()" because "lyrics" is null
	at dev.spoocy.genius.Main.main(Main.java:32)

**Comment by Spoocy99** [comment]
Currently can't seem to recreate the issue. 
If using a VPS or proxy you are very likely to get a 403 error because of Genius's captcha service.

On the other side this can be related to the user agent used in the request header. 
A new release has been deployed to use the correct user agent. Be sure to specify a custom user agent in the GeniusClientBuilder if needed.

 If the issue persist please provide more information on how to recreate this issue.
